import Head from 'next/head'
//import Image from 'next/image'
import React, { useState } from 'react'
import styles from '../styles/Navbar.module.css'

export default function Navbar() {
 
  return (
    <div className={styles.nav}>
      <Head>
        <title>Alkemy's Superhero team builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"></link>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"></link>
      </Head>
        <navbar>
            <h3>Alkemy's React challenge</h3>
        </navbar>
    </div>
  )
}
